---
user: grit 
group: web 
environment: development 
timeout: 30
wait: 30
log: log/thin.log
chdir: /var/www/haveyourdessert/
max_conns: 1024
max_persistent_conns: 512 
require: []
threaded: true
servers: 3
daemonize: true
no-epoll: true
pid: tmp/pids/thin.pid
socket: tmp/thin.sock
tag: thin-server

